// Shared helpers for the build and verification scripts.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SITE = path.join(ROOT, 'site');
export const SALT = 'wrenfield/wa-001';

/** Run a classic browser script (site/js/*.js) in a sandbox and return what it put on `window`. */
export function loadBrowserScript(file, extra = {}) {
  const code = fs.readFileSync(path.join(SITE, 'js', file), 'utf8');
  const sandbox = { TextEncoder, TextDecoder, btoa, atob, escape, unescape, encodeURIComponent, decodeURIComponent, Math, ...extra };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: file });
  return sandbox;
}

export const loadSeal = () => loadBrowserScript('seal.js').Seal;
export const loadSound = () => loadBrowserScript('audio.js').Sound;

/** Import every content module fresh (no module cache), so edits are always picked up. */
export async function loadContent() {
  const stamp = Date.now();
  const imp = async (name) => (await import(pathToFileURL(path.join(ROOT, 'src/content', name)).href + '?v=' + stamp)).default;
  const cases = {};
  for (let n = 1; n <= 6; n++) cases[n] = await imp(`case${n}.js`);
  return { cases, deep: await imp('deep.js'), answers: await imp('answers.js'), config: await imp('config.js') };
}

const clone = (o) => JSON.parse(JSON.stringify(o));

/** Build the vault object: case 1 in the clear, everything else sealed. */
export function buildVault({ cases, deep, answers }, Seal) {
  const prepared = {};
  for (let n = 1; n <= 6; n++) {
    const c = clone(cases[n]);
    // The 'show me the key' answer is sealed too, so it never sits in the page source as plain text.
    if (n <= 5) c.reveal = Seal.seal(answers['c' + n].key, 'REVEAL', 'c' + n + ':reveal', SALT);
    if (n === 4) {
      const box = c.evidence.find((e) => e.type === 'lockbox');
      box.data.lockTag = Seal.tag(answers.lock, 'lock', SALT);
    }
    if (n === 6) c.doorReveal = Seal.seal(answers.deep.key, 'REVEAL', 'deep:reveal', SALT);
    prepared[n] = c;
  }

  const seal = (scope, data, ans) => {
    const key = Seal.normalize(ans.key);
    const alts = [...new Set((ans.alts || []).map(Seal.normalize))].filter((a) => a && a !== key);
    return {
      d: Seal.seal(JSON.stringify(data), key, scope, SALT),
      alt: alts.map((a) => ({ t: Seal.tag(a, scope + ':alt', SALT), k: Seal.seal(key, a, scope + ':alt', SALT) })),
      near: Object.entries(ans.near || {}).map(([word, msg]) => ({
        t: Seal.tag(word, scope + ':near', SALT),
        m: Seal.seal(msg, word, scope + ':near', SALT),
      })),
    };
  };

  const sealed = {};
  for (let n = 2; n <= 6; n++) sealed['c' + n] = seal('c' + n, prepared[n], answers['c' + (n - 1)]);
  sealed.deep = seal('deep', clone(deep), answers.deep);

  return {
    v: 1,
    salt: SALT,
    index: [1, 2, 3, 4, 5, 6].map((n) => ({ code: cases[n].code, title: cases[n].title })),
    c1: prepared[1],
    sealed,
  };
}

export function vaultSource(vault) {
  return '/* GENERATED by tools/build.mjs from src/content. Do not edit by hand: run `npm run build`. */\n' +
    'window.VAULT = ' + JSON.stringify(vault) + ';\n';
}

/** Inline CSS, fonts, icon and scripts into one self-contained HTML document. */
export function standaloneHtml() {
  let html = fs.readFileSync(path.join(SITE, 'index.html'), 'utf8');
  const dataUri = (file, type) => `data:${type};base64,${fs.readFileSync(path.join(SITE, file)).toString('base64')}`;
  let css = fs.readFileSync(path.join(SITE, 'css/style.css'), 'utf8');
  css = css.replace(/url\(\.\.\/(assets\/fonts\/[^)]+\.woff2)\)/g, (_, f) => `url(${dataUri(f, 'font/woff2')})`);
  html = html.replace(/\s*<link rel="preload"[^>]*>/g, '');
  html = html.replace('<link rel="stylesheet" href="css/style.css">', () => `<style>\n${css}\n</style>`);
  html = html.replace('href="assets/favicon.svg"', () => `href="${dataUri('assets/favicon.svg', 'image/svg+xml')}"`);
  html = html.replace(/<script src="js\/([\w.-]+)"><\/script>/g, (_, f) => {
    const js = fs.readFileSync(path.join(SITE, 'js', f), 'utf8').replace(/<\/script/gi, '<\\/script');
    return `<script>\n${js}\n</script>`;
  });
  return html;
}

/** The same page as a body fragment, for hosts that supply their own <head>. */
export function fragmentHtml(full) {
  const title = full.match(/<title>[\s\S]*?<\/title>/)[0];
  const style = full.match(/<style>[\s\S]*?<\/style>/)[0];
  const body = full.match(/<body>([\s\S]*)<\/body>/)[1];
  return `${title}\n${style}\n${body}`;
}
